### ISSUE TITLE
Add check variables workflow

### ISSUE THREAD

**Issue by thibaultserti** [thibaultserti/gh-actions-reusable-workflows#11]

**Comment by thibaultserti** [comment]
```yaml
name: Vérifier la présence de secrets

on: [push, pull_request]

jobs:
  check-secrets:
    runs-on: ubuntu-latest

    inputs:
      secrets-list:
        description: 'Liste des secrets à vérifier'
        required: true

    steps:
      - name: Vérifier la présence des secrets
        env:
          SECRETS_LIST: ${{ github.event.inputs.secrets-list }}
        run: |
          for SECRET_NAME in $SECRETS_LIST; do
            if [ -z "${{ secrets.${SECRET_NAME} }}" ]; then
              echo "Le secret $SECRET_NAME est manquant."
              exit 1
            else
              echo "Le secret $SECRET_NAME est présent."
            fi
          done
```
